documentation for access control of shells
eclipse-tractusx/sldt-digital-twin-registry pull request #200
Opened 2023-08-23 12:27 UTC by tunacicek

## Description
Add documentation for access control of shells

2023-08-24 09:09 UTC, bs-sili commented on docs/README.md
> +* Only those users, where `externalSubjectId` matches the Eclipse Dataspace Components-Header (*i.e.* BPN) are able to discover via and read exactly this content of `specificAssetIds`.
Wouldn't make it more sense to to write this sentence "...  are able to discover and read ..."? So without "via"?

2023-08-24 09:09 UTC, bs-sili commented on docs/README.md
> +      * `extensions`
Shouldn't we delete the "extensions" as the DTR do not provide this field?

2023-08-29 07:06 UTC, thomas-henn requested changes

2023-08-29 07:06 UTC, thomas-henn commented on docs/README.md
> +The defined character for `"PUBLIC_READABLE"` and the list of allowed types to mark as public is configurable via helm values.yml:
The defined string...

2023-08-29 08:45 UTC, thomas-henn commented
Behavior of Digital Twin Registry with respect to read access to digital twins is described here as aligned with the users of this application.

2023-08-29 08:46 UTC, thomas-henn commented
Behavior of Digital Twin Registry with respect to read access to digital twins is described here as aligned with the users of this application.

2023-08-29 08:54 UTC, thomas-henn commented
Behavior of Digital Twin Registry with respect to read access to digital twins is described here as aligned with the users of this application.

2023-08-29 08:59 UTC, merged