Fix: Removed licenses step from action
eclipse-tractusx/sldt-digital-twin-registry pull request #436
Opened 2024-07-03 13:21 UTC by agg3fe

## Description
Fixing broken pipe line issue after adding mandatory new licenses

2024-07-03 13:40 UTC, tunacicek commented on .github/workflows/publish-image-registry.yml
> -      - name: dependency-licenses
Why is this task removed? 
We need dependencies-notice

2024-07-03 14:06 UTC, tunacicek commented
@agg3fe : If the steps for licenses are removed, we need to find a way to copy the required file into the Docker image. For example in the dockerfile.

2024-07-03 14:06 UTC, tunacicek requested changes
If the steps for licenses are removed, we need to find a way to copy the required file into the Docker image. For example in the dockerfile.

2024-07-05 10:39 UTC, agg3fe commented
> @agg3fe : If the steps for licenses are removed, we need to find a way to copy the required file into the Docker image. For example in the dockerfile.

@tunacicek PR is updated.

2024-07-05 11:14 UTC, tunacicek approved these changes
LGTM

2024-07-05 11:14 UTC, merged